
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveDatabaseUrl } from "./lib/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Must resolve the same way `lib/db.ts` does (see lib/database-url.ts) —
    // otherwise `prisma migrate`/`db push` and the app/seed script silently
    // target two different SQLite files.
    url: resolveDatabaseUrl(),
  },
});
